export const ADD_PRODUCT_START = "ADD_PRODUCT_START";
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS"
export const ADD_PRODUCT_INITIATE = "ADD_PRODUCT_INITIATE";
//
//
//
export const UPLOAD_LIST_START = "UPLOAD_LIST_START";
export const UPLOAD_LIST_FAIL = "UPLOAD_LIST_FAIL";
export const UPLOAD_LIST_SUCCESS = "UPLOAD_LIST_SUCCESS";
export const UPLOAD_LIST_INITIATE = "UPLOAD_LIST_INITIATE";
//
//
//
export const REMOVE_PRODUCT_START = "REMOVE_PRODUCT_START";
export const REMOVE_PRODUCT_FAIL = "REMOVE_PRODUCT_FAIL";
export const REMOVE_PRODUCT_SUCCESS = "REMOVE_PRODUCT_SUCCESS";
export const REMOVE_PRODUCT_INITIATE = "REMOVE_PRODUCT_INITIATE";